account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.UserDashboardView.as_view() ,name='user_dashboard'),
    path('login/', views.UserLoginView.as_view() ,name='user_login'),
    path('logout/', views.UserLogoutView.as_view() ,name='user_logout'),
    path('register/', views.UserRegisterView.as_view() ,name='user_register'),
    path('profile/<slug:username>', views.UserProfileView.as_view() ,name='user_profile'),
    path('profile/', views.AuthorListView.as_view() ,name='author_profile'),
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='blog'),
    re_path(r'^(?P<slug>[-\w\u0600-\u06FF]+)/$', views.ArticleDetailView.as_view(), name='article'),
]

home/urls.py
from django.urls import path
from. import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePageView.as_view() , name='home'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from django.utils.text import slugify

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='articles')
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, allow_unicode=True, null=True)
    head_content = models.TextField(blank=True)
    body = models.TextField()
    foot_content = models.TextField(blank=True)
    short_description = models.CharField(max_length=500, blank=True)
    image = models.ImageField(upload_to='blog_images/')
    date = models.DateField(auto_now_add=True)

    def short_body(self):
        return self.body[:300]
    def short_foot(self):
        return self.foot_content[:300]
    def short_head(self):
        return self.head_content[:300]

    def save(self, *args, **kwargs):

        if not self.slug:
            self.slug = slugify(self.title,allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.author} / {self.title}"

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from account.models import Profile
from blog.models import Article


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/blog_list.html'
    context_object_name = "articles"
    queryset = Article.objects.all()
    ordering = ['-date']
    paginate_by = 3
    paginate_orphans = 1

class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/blog_detail.html'
    context_object_name = 'article'
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.author:
            context['related_article'] = Article.objects.filter(author=self.object.author).exclude(pk=self.object.pk)
            context['author_profile'] = Profile.objects.get(user=self.object.author)
        else:
            context['related_article'] = []
            context['author_profile'] = None

        return context

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Blog Detail
{% endblock %}
{% block content %}


    <div class="first-widget parallax" id="blogId">
        <div class="parallax-overlay">
            <div class="container pageTitle">
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <h2 class="page-title">جزییات مقاله</h2>
                    </div> <!-- /.col-md-6 -->
                    <div class="col-md-6 col-sm-6 text-right">
						<span class="page-location"><a href="{% url 'home:home' %}">خانه / <a
                                href="{% url 'blog:blog' %}">مقالات /
                        <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a></a></a></span>
                    </div> <!-- /.col-md-6 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.parallax-overlay -->
    </div> <!-- /.pageTitle -->

    <div class="container">
        <div class="row">

            <div class="col-md-8 blog-posts">
                <div class="row">
                    <div class="col-md-12">
                        <div class="post-blog">
                            <div class="blog-image">
                                <img src="{{ article.image.url }}" alt="">
                            </div> <!-- /.blog-image -->
                            <div class="blog-content">
                                <span class="meta-date"><a href="#">{{ article.date }}</a></span>
                                <span class="meta-comments"><a href="#blog-comments">3 Comments</a></span>
                                <span class="meta-author"><a href="#blog-author">{{ article.author }}</a></span>
                                <h3>{{ article.title }}</h3>
                                {% if article.head_content %}
                                    <p>{{ article.head_content }}</p>
                                {% endif %}
                                <blockquote>
                                    {% if article.short_head %}
                                        <p>{{ article.short_head }}</p>
                                    {% endif %}
                                    <p>{{ article.short_body }}</p>
                                    {% if article.short_foot %}
                                        <p>{{ article.short_foot }}</p>
                                    {% endif %}
                                </blockquote>
                                <p>{{ article.body }}.</p>
                                {% if article.foot_content %}
                                    <p>{{ article.foot_content }}</p>
                                {% endif %}
                                <div class="tag-items">
                                    <span class="small-text">Tags:</span>
                                    <a href="#" rel="tag">business</a>
                                    <a href="#" rel="tag">html</a>
                                    <a href="#" rel="tag">education</a>
                                </div>
                            </div> <!-- /.blog-content -->
                        </div> <!-- /.post-blog -->
                    </div> <!-- /.col-md-12 -->
                </div> <!-- /.row -->
                <div class="row">
                    <div class="col-md-12">
                        <div id="blog-author" class="clearfix">
                            <a href="#" class="blog-author-img pull-left">
                                <img src="{{ author_profile.avatar.url }}" alt="{{ author_profile.user.username}}">
                            </a>
                            <div class="blog-author-info">
                                <h4 class="author-name"><a href="{% url 'account:user_profile' username=article.author.username %}">{{ article.author }}</a></h4>
                                <p>{{ user.bio }}</p>
                            </div>
                        </div>
                    </div> <!-- /.col-md-12 -->
                </div> <!-- /.row -->
                <div class="row">
                    <div class="col-md-12">
                        <div id="blog-comments" class="blog-post-comments">
                            <h3>3 Comments</h3>
                            <div class="blog-comments-content">
                                <div class="media">
                                    <div class="pull-left">
                                        <img class="media-object" src="images/includes/comment1.jpg" alt="">
                                    </div>
                                    <div class="media-body">
                                        <div class="media-heading">
                                            <h4>Linda Wilson</h4>
                                            <a href="#"><span>4 weeks ago</span><span>Reply</span></a>
                                        </div>
                                        <p>Lorem ipsum dolor sit amet lorem, elit. Sequi, nam magni repellendus! <span
                                                class="label label-primary">New</span></p>
                                        <div class="media">
                                            <div class="pull-left">
                                                <img class="media-object" src="images/includes/comment2.jpg" alt="">
                                            </div>
                                            <div class="media-body">
                                                <div class="media-heading">
                                                    <h4>Stephen</h4>
                                                    <a href="#"><span>5 weeks ago</span><span>Reply</span></a>
                                                </div>
                                                <p>Temporibus, ea, praesentium eaque totam vel quos laboriosam quia sit
                                                    dolore at consequatur beatae aliquam debitis porro quasi cupiditate
                                                    quod!</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="media">
                                    <div class="pull-left">
                                        <img class="media-object" src="images/includes/comment3.jpg" alt="">
                                    </div>
                                    <div class="media-body">
                                        <div class="media-heading">
                                            <h4>Marco New</h4>
                                            <a href="#"><span>6 weeks ago</span><span>Reply</span></a>
                                        </div>
                                        <p>Enim, iste numquam inventore reiciendis libero quidem quos voluptate? Thank
                                            you for visiting templatemo.</p>
                                    </div>
                                </div>
                            </div> <!-- /.blog-comments-content -->
                        </div> <!-- /.blog-post-comments -->
                    </div> <!-- /.col-md-12 -->
                </div> <!-- /.row -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="comment-form">
                            <h3>Leave a comment</h3>
                            <div class="widget-inner">
                                <form action="#" method="post">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <p>
                                                <label for="name-id">Your Name:</label>
                                                <input type="text" id="name-id" name="name-id">
                                            </p>
                                        </div>
                                        <div class="col-md-4">
                                            <p>
                                                <label for="email-id">Email Address:</label>
                                                <input type="text" id="email-id" name="email-id">
                                            </p>
                                        </div>
                                        <div class="col-md-4">
                                            <p>
                                                <label for="site-id">Your Site:</label>
                                                <input type="text" id="site-id" name="site-id">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <p>
                                                <label for="comment">Your comment:</label>
                                                <textarea name="comment" id="comment" rows="5"></textarea>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input class="mainBtn" type="submit" name="submit" value="Submit Comment"
                                                   id="submit">
                                        </div>
                                    </div>
                                </form>
                            </div> <!-- /.widget-inner -->
                        </div> <!-- /.widget-main -->
                    </div> <!-- /.col-md-12 -->
                </div> <!-- /.row -->
            </div> <!-- /.col-md-8 -->

            <div class="col-md-4">
                <div class="sidebar">
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Recent Posts</h5>
                        <div class="last-post clearfix">
                            <div class="thumb pull-left">
                                <a href="#"><img src="images/includes/blogthumb1.jpg" alt=""></a>
                            </div>
                            <div class="content">
                                <span>24 February 2084</span>
                                <h4><a href="#">Standard Post Formating Medigo</a></h4>
                            </div>
                        </div> <!-- /.last-post -->
                        <div class="last-post clearfix">
                            <div class="thumb pull-left">
                                <a href="#"><img src="images/includes/blogthumb2.jpg" alt=""></a>
                            </div>
                            <div class="content">
                                <span>24 February 2084</span>
                                <h4><a href="#">Standard Post Formating Medigo</a></h4>
                            </div>
                        </div> <!-- /.last-post -->
                        <div class="last-post clearfix">
                            <div class="thumb pull-left">
                                <a href="#"><img src="images/includes/blogthumb3.jpg" alt=""></a>
                            </div>
                            <div class="content">
                                <span>24 February 2084</span>
                                <h4><a href="#">Standard Post Formating Medigo</a></h4>
                            </div>
                        </div> <!-- /.last-post -->
                    </div> <!-- /.sidebar-widget -->
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Categories</h5>
                        <div class="row categories">
                            <div class="col-md-6">
                                <ul>
                                    <li><a href="#">Standard</a></li>
                                    <li><a href="#">Audio</a></li>
                                    <li><a href="#">Video</a></li>
                                    <li><a href="#">Branding</a></li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li><a href="#">iOS Design</a></li>
                                    <li><a href="#">Business</a></li>
                                </ul>
                            </div>
                        </div> <!-- /.row -->
                    </div> <!-- /.sidebar-widget -->
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Flickr Feed</h5>
                        <ul id="flickr-feed" class="thumbs"></ul>
                    </div> <!-- /.sidebar-widget -->
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Text Widget</h5>
                        <p class="light-text">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
                            ut fermentum massa justo sit amet risus. Cum sociis natoque penatibus et magnis dis
                            parturient… </p>
                    </div> <!-- /.sidebar-widget -->
                </div> <!-- /.sidebar -->
            </div> <!-- /.col-md-4 -->

        </div> <!-- /.row -->
    </div> <!-- /.container -->
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Blog
{% endblock %}
{% block content %}

    <div class="first-widget parallax" id="blog">
        <div class="parallax-overlay">
            <div class="container pageTitle">
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <h2 class="page-title">مقالات</h2>
                    </div> <!-- /.col-md-6 -->
                    <div class="col-md-6 col-sm-6 text-right">
                        <span class="page-location"><a href="{% url 'home:home' %}">خانه / <a href="{% url 'blog:blog'%}">مقالات</a></a></span>
                    </div> <!-- /.col-md-6 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.parallax-overlay -->
    </div> <!-- /.pageTitle -->

    <div class="container">
        <div class="row">

            <div class="col-md-8 blog-posts">
                <div class="row">
                    <div class="col-md-12">
                        {% for article in articles %}
                            <div class="post-blog">
                                <div class="blog-image">
                                    <a href="{% url 'blog:article' article.slug %}">
                                        <img src="{{ article.image.url }}" alt="{{ article.author }}">
                                    </a>
                                </div> <!-- /.blog-image -->
                                <div class="blog-content">
                                    <span class="meta-date"><a href="#">{{ article.date }}</a></span>
                                    <span class="meta-comments"><a href="#">Comments</a></span>
                                    <span class="meta-author"><a href="{% url 'account:user_profile' username=article.author.username %}">{{ article.author }}</a></span>
                                    <h3><a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a></h3>
                                    <p class="light-text">{{ article.short_description }}</p>
                                    <p>{{ article.short_body }}<a href="{% url 'blog:article' article.slug %}">ادامه مطالب</a></p>
                                </div> <!-- /.blog-content -->
                            </div> <!-- /.post-blog -->
                        {% endfor %}

                    </div> <!-- /.col-md-12 -->
                    <div class="col-md-12">
                        {% if is_paginated %}
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">

                                    {# دکمه قبلی #}
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">>></a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"></li>
                                    {% endif %}

                                    {# شماره صفحه فعلی و قبلی و بعدی فقط #}
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                                        </li>
                                    {% endif %}

                                    <li class="page-item active" aria-current="page">
                                        <a class="page-link"
                                           href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                                    </li>

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                                        </li>
                                    {% endif %}

                                    {# دکمه بعدی #}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"><<</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"></li>
                                    {% endif %}

                                </ul>
                            </nav>
                        {% endif %}


                    </div> <!-- /.col-md-12 -->
                </div> <!-- /.row -->
            </div> <!-- /.col-md-8 -->

            <div class="col-md-4">
                <div class="sidebar">
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Recent Posts</h5>
                        <div class="last-post clearfix">
                            <div class="thumb pull-left">
                                <a href="#"><img src="{% static 'images/includes/blogthumb1.jpg' %}" alt=""></a>
                            </div>
                            <div class="content">
                                <span>24 February 2084</span>
                                <h4><a href="#">Standard Post Formating Medigo</a></h4>
                            </div>
                        </div> <!-- /.last-post -->
                        <div class="last-post clearfix">
                            <div class="thumb pull-left">
                                <a href="#"><img src="{% static 'images/includes/blogthumb2.jpg' %}" alt=""></a>
                            </div>
                            <div class="content">
                                <span>24 February 2084</span>
                                <h4><a href="#">Standard Post Formating Medigo</a></h4>
                            </div>
                        </div> <!-- /.last-post -->
                        <div class="last-post clearfix">
                            <div class="thumb pull-left">
                                <a href="#"><img src="{% static 'images/includes/blogthumb3.jpg' %}" alt=""></a>
                            </div>
                            <div class="content">
                                <span>24 February 2084</span>
                                <h4><a href="#">Standard Post Formating Medigo</a></h4>
                            </div>
                        </div> <!-- /.last-post -->
                    </div> <!-- /.sidebar-widget -->
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Categories</h5>
                        <div class="row categories">
                            <div class="col-md-6">
                                <ul>
                                    <li><a href="#">Standard</a></li>
                                    <li><a href="#">Audio</a></li>
                                    <li><a href="#">Video</a></li>
                                    <li><a href="#">Branding</a></li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li><a href="#">iOS Design</a></li>
                                    <li><a href="#">Business</a></li>
                                </ul>
                            </div>
                        </div> <!-- /.row -->
                    </div> <!-- /.sidebar-widget -->
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Flickr Feed</h5>
                        <ul id="flickr-feed" class="thumbs"></ul>
                    </div> <!-- /.sidebar-widget -->
                    <div class="sidebar-widget">
                        <h5 class="widget-title">Text Widget</h5>
                        <p class="light-text">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
                            ut fermentum massa justo sit amet risus. Cum sociis natoque penatibus et magnis dis
                            parturient… </p>
                    </div> <!-- /.sidebar-widget -->
                </div> <!-- /.sidebar -->
            </div> <!-- /.col-md-4 -->

        </div> <!-- /.row -->
    </div> <!-- /.container -->

{% endblock %}