account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.UserDashboardView.as_view() ,name='user_dashboard'),
    path('login/', views.UserLoginView.as_view() ,name='user_login'),
    path('logout/', views.UserLogoutView.as_view() ,name='user_logout'),
    path('register/', views.UserRegisterView.as_view() ,name='user_register'),
    path('profile/<slug:username>', views.UserProfileView.as_view() ,name='user_profile'),
    path('profile/', views.AuthorListView.as_view() ,name='author_profile'),
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='blog'),
    re_path(r'^(?P<slug>[-\w\u0600-\u06FF]+)/$', views.ArticleDetailView.as_view(), name='article'),
]

home/urls.py
from django.urls import path
from. import views

app_name = 'home'

urlpatterns = [
    path('', views.HomePageView.as_view() , name='home'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa-ir" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="templatemo">
    <!--
	Medigo Template
	http://www.templatemo.com/preview/templatemo_460_medigo
    -->

    <!-- Google Fonts -->
    <link href="http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700itali" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Raleway:400,900,800,700,500,200,100,600" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/misc.css' %}">
    <link rel="stylesheet" href="{% static 'css/blue-scheme.css' %}">

    <!-- JavaScripts -->
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon"/>

</head>
<body>
<div class="responsive_menu">
    <ul class="main_menu">
        <li><a href="{% url 'home:home' %}">خانه</a></li>
        <li class="{% if request.resolver_match.url_name == 'user_dashboard' %}active{% endif %}">
            {% if user.is_authenticated %}
                <a href="{% url 'account:user_dashboard' %}">
                    <img src="{{ user.profile.avatar.url }}"
                         style="width:28px;height:28px;border-radius:50%;vertical-align:middle;"
                         alt="avatar">
                    <span style="margin-right:6px;">
                            {% if user.get_full_name %}
                                {{ user.get_full_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </span>
                </a>
            {% else %}
                <a href="#">حساب کاربری</a>
            {% endif %}
            <ul>
                {% if user.is_authenticated %}

                    <li>
                        <form method="post" action="{% url 'account:user_logout' %}">
                            {% csrf_token %}
                            <button style="color: red" type="submit" class="btn btn-link">خروج از حساب</button>
                        </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">ورود به حساب</a></li>
                    <li><a href="{% url 'account:user_register' %}">ثبت نام</a></li>
                {% endif %}
            </ul>
        </li>
        <li><a href="{% url 'blog:blog' %}">وبلاگ</a>
            <ul>
                <li><a href="blog.html">دسته بندی ها</a></li>
                <li><a href="blog-single.html">نویسندگان</a></li>
                <li><a href="#">visit templatemo</a></li>
            </ul>
        </li>
        <li><a href="archives.html">آرشیو ها</a></li>
        <li><a href="contact.html">تماس با ما</a></li>
    </ul> <!-- /.main_menu -->
</div> <!-- /.responsive_menu -->

<header class="site-header clearfix">
    <div class="container">

        <div class="row">

            <div class="main-navigation pull-left">
                <nav class="main-nav visible-md visible-lg">
                    <ul class="sf-menu">
                        <li class="{% if request.resolver_match.url_name == 'user_dashboard' %}active{% endif %}">
                            {% if user.is_authenticated %}
                                <a href="{% url 'account:user_dashboard' %}">
                                    <img src="{{ user.profile.avatar.url }}"
                                         style="width:28px;height:28px;border-radius:50%;vertical-align:middle;"
                                         alt="avatar">
                                    <span style="margin-right:6px;">
                            {% if user.get_full_name %}
                                {{ user.get_full_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </span>
                                </a>
                            {% else %}
                                <a href="#">حساب کاربری</a>
                            {% endif %}
                            <ul>
                                {% if user.is_authenticated %}
                                    <li>
                                        <form method="post" action="{% url 'account:user_logout' %}">
                                            {% csrf_token %}
                                            <button style="color: red" type="submit" class="btn btn-link">خروج از حساب
                                            </button>
                                        </form>
                                    </li>
                                {% else %}
                                    <li><a href="{% url 'account:user_login' %}">ورود به حساب</a></li>
                                    <li><a href="{% url 'account:user_register' %}">ثبت نام </a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>

            <div class="main-navigation pull-right">

                <nav class="main-nav visible-md visible-lg">
                    <ul class="sf-menu">
                        <li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}"><a
                                href="{% url 'home:home' %}">خانه</a></li>

                        <li class="{% if request.resolver_match.url_name == 'blog' %}active{% endif %}"><a
                                href="{% url 'blog:blog' %}">وبلاگ</a>
                            <ul>
                                <li><a href="blog.html">دسته بندی ها</a></li>
                                <li><a href="blog-single.html">نویسندگان</a></li>
                                <li><a href="#">visit templatemo</a></li>
                            </ul>
                        </li>
                        <li><a href="archives.html">آرشیو ها</a></li>
                        <li><a href="contact.html">تماس با ما</a></li>
                    </ul> <!-- /.sf-menu -->
                </nav> <!-- /.main-nav -->

                <!-- This one in here is responsive menu for tablet and mobiles -->
                <div class="responsive-navigation visible-sm visible-xs">
                    <a href="#nogo" class="menu-toggle-btn">
                        <i class="fa fa-bars"></i>
                    </a>
                </div> <!-- /responsive_navigation -->

            </div> <!-- /.main-navigation -->

        </div> <!-- /.col-md-12 -->

    </div> <!-- /.row -->

    <!-- /.container -->
</header> <!-- /.site-header -->


{% block content %}


{% endblock %}


<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="footer-nav clearfix">
                    <ul class="footer-menu">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li><a href="blog.html">Blog Posts</a></li>
                        <li><a href="archives.html">Shortcodes</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul> <!-- /.footer-menu -->
                </nav> <!-- /.footer-nav -->
            </div> <!-- /.col-md-12 -->
        </div> <!-- /.row -->
        <div class="row">
            <div class="col-md-12">
                <p class="copyright-text">Copyright &copy; 2084 Company Name
                    | Design: templatemo</p>
            </div> <!-- /.col-md-12 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</footer> <!-- /.site-footer -->

<!-- Scripts -->
<script src="{% static 'js/min/plugins.min.js' %}"></script>
<script src="{% static 'js/min/medigo-custom.min.js' %}"></script>

</body>
</html>